; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Undertale:
; FAMISTUDIO_EXP_VRC6 = 1
; FAMISTUDIO_USE_VOLUME_TRACK = 1
; FAMISTUDIO_USE_VOLUME_SLIDES = 1
; FAMISTUDIO_USE_PITCH_TRACK = 1
; FAMISTUDIO_USE_SLIDE_NOTES = 1
; FAMISTUDIO_USE_VIBRATO = 1
; FAMISTUDIO_USE_ARPEGGIO = 1
; FAMISTUDIO_USE_DUTYCYCLE_EFFECT = 1
; FAMISTUDIO_USE_DPCM_BANKSWITCHING = 1

.export _music_data_undertale:=music_data_undertale

music_data_undertale:
	.byte 4
	.word @instruments
	.word @samples-5
; 00 : 1.Once Upon A Time
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word @song0ch5
	.word @song0ch6
	.word @song0ch7
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 01 : 50.Metal Crusher
	.word @song1ch0
	.word @song1ch1
	.word @song1ch2
	.word @song1ch3
	.word @song1ch4
	.word @song1ch5
	.word @song1ch6
	.word @song1ch7
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 02 : 100.Megalovania
	.word @song2ch0
	.word @song2ch1
	.word @song2ch2
	.word @song2ch3
	.word @song2ch4
	.word @song2ch5
	.word @song2ch6
	.word @song2ch7
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0
; 03 : sfx
	.word @song3ch0
	.word @song3ch1
	.word @song3ch2
	.word @song3ch3
	.word @song3ch4
	.word @song3ch5
	.word @song3ch6
	.word @song3ch7
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_undertale
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env12,@env22,@env23,@env1 ; 00 : OH F3
	.word @env7,@env10,@env23,@env1 ; 01 : CH F3
	.word @env15,@env19,@env25,@env1 ; 02 : Opening Lead (Once Upon A Time)
	.word @env8,@env19,@env33,@env9 ; 03 : Lead Megalovania
	.word @env20,@env19,@env3,@env11 ; 04 : Lead2
	.word @env14,@env19,@env4,@env1 ; 05 : Duty 210
	.word @env17,@env19,@env21,@env1 ; 06 : Guitar VRC6
	.word @env14,@env19,@env23,@env27 ; 07 : Vibrate
	.word @env14,@env19,@env28,@env1 ; 08 : Duty 210 VRC6
	.word @env14,@env19,@env23,@env1 ; 09 : Base
	.word @env32,@env19,@env25,@env1 ; 0a : Jangle [Quiet Part] (Once Upon A Time) 1
	.word @env5,@env19,@env24,@env1 ; 0b : 50% ARP (Once Upon A Time
	.word @env26,@env19,@env25,@env1 ; 0c : Opening Lead [Quiet Part] (Once Upon A Time)
	.word @env18,@env19,@env23,@env1 ; 0d : Jangle (Once Upon A Time)
	.word @env0,@env19,@env25,@env1 ; 0e : Attack Lead (Once Upon A Time)
	.word @env16,@env19,@env23,@env1 ; 0f : Noise Drums (Once Upon A Time)
	.word @env2,@env34,@env23,@env1 ; 10 : Bass VRC6

@env0:
	.byte $00,$c2,$c3,$c7,$ca,$cf,$00,$05
@env1:
	.byte $00,$c0,$7f,$00,$02
@env2:
	.byte $00,$cd,$cd,$cc,$cc,$ca,$c9,$c8,$c6,$c4,$05,$c3,$c3,$c2,$00,$0d
@env3:
	.byte $c1,$c2,$00,$01
@env4:
	.byte $c2,$c2,$c1,$c1,$c0,$00,$04
@env5:
	.byte $00,$cf,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$00,$0f
@env6:
	.byte $c0,$cc,$cc,$c0,$00,$00
@env7:
	.byte $00,$cf,$02,$c8,$c0,$00,$04
@env8:
	.byte $0e,$ce,$cd,$cc,$cc,$cb,$cb,$ca,$c9,$c9,$c8,$c8,$00,$0b,$c7,$04,$c6,$04,$c5,$c5,$c4,$c4,$c3,$03,$c2,$c2,$c1,$00,$1a
@env9:
	.byte $00,$bf,$7f,$00,$02
@env10:
	.byte $c0,$c3,$c5,$00,$02
@env11:
	.byte $00,$c0,$11,$c0,$c2,$c4,$c6,$c4,$c2,$c0,$be,$bc,$ba,$bc,$be,$00,$03
@env12:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$10
@env13:
	.byte $c0,$b4,$b4,$c0,$00,$00
@env14:
	.byte $00,$cf,$7f,$00,$02
@env15:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$00,$0f
@env16:
	.byte $00,$cf,$02,$c7,$c2,$c0,$00,$05
@env17:
	.byte $00,$cf,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$06,$c2,$06,$c1,$00,$0f
@env18:
	.byte $00,$cf,$02,$cd,$cb,$ca,$c8,$c7,$c6,$c5,$c4,$c2,$00,$0b
@env19:
	.byte $c0,$7f,$00,$01
@env20:
	.byte $00,$cf,$cd,$cb,$c9,$c8,$00,$05
@env21:
	.byte $c6,$c4,$00,$01
@env22:
	.byte $c0,$c1,$c2,$00,$02
@env23:
	.byte $7f,$00,$00
@env24:
	.byte $c2,$7f,$00,$00
@env25:
	.byte $c1,$7f,$00,$00
@env26:
	.byte $00,$c1,$c2,$c1,$00,$03
@env27:
	.byte $00,$c0,$c2,$c3,$c2,$c0,$be,$bd,$be,$00,$01
@env28:
	.byte $c7,$c7,$c3,$c3,$c1,$00,$04
@env29:
	.byte $00,$c0,$be,$bc,$bc,$bd,$bf,$c1,$c3,$c4,$c4,$c2,$00,$01
@env30:
	.byte $00,$c0,$bf,$be,$bd,$bd,$be,$bf,$c1,$c2,$c3,$c3,$c2,$c1,$00,$01
@env31:
	.byte $00,$c0,$bf,$be,$02,$bf,$c0,$c0,$c1,$c2,$02,$c1,$00,$01
@env32:
	.byte $00,$c3,$c4,$c3,$00,$03
@env33:
	.byte $c2,$c2,$c1,$00,$02
@env34:
	.byte $cc,$c0,$00,$01

@samples:
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0e,$40,$01 ; 00 Impact_Hit_D5 (Pitch:14)
	.byte $40+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$01 ; 01 Impact_Hit_D5 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$01 ; 02 Impact_Hit_E5 (Pitch:15)
	.byte $23+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0e,$40,$00 ; 03 Impact_Hit_F5 (Pitch:14)
	.byte $23+.lobyte(FAMISTUDIO_DPCM_PTR),$ff,$0f,$40,$00 ; 04 Impact_Hit_F5 (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$4a,$0f,$40,$00 ; 05 MG KICK (Pitch:15)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$34,$0f,$40,$02 ; 06 MG SNARE (Pitch:15)
	.byte $1a+.lobyte(FAMISTUDIO_DPCM_PTR),$fd,$0f,$40,$02 ; 07 mus_intronoise (Pitch:15)
	.byte $13+.lobyte(FAMISTUDIO_DPCM_PTR),$1d,$0f,$40,$00 ; 08 nes_drumkit_0 (Pitch:15)
	.byte $0d+.lobyte(FAMISTUDIO_DPCM_PTR),$32,$0f,$40,$02 ; 09 nes_drumkit_2 (Pitch:15)
	.byte $1b+.lobyte(FAMISTUDIO_DPCM_PTR),$1e,$0f,$40,$00 ; 0a nes_drumkit_3 (Pitch:15)
	.byte $63+.lobyte(FAMISTUDIO_DPCM_PTR),$6a,$0f,$40,$00 ; 0b snd_power (Pitch:15)

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $49, .lobyte(@env1), .hibyte(@env1), $4a, $84
@song0ref6:
	.byte $25, $eb, $31, $eb, $48, $2c, $eb, $00, $eb, $48, $2a, $eb, $31, $eb, $48, $25, $eb, $00, $eb, $48, $25, $eb, $2a, $eb
	.byte $48, $31, $eb, $33, $eb, $48, $31, $eb, $2c, $eb, $48, $2a, $eb, $00, $eb, $48, $49, .lobyte(@env1), .hibyte(@env1)
	.byte $4a
	.byte $41, $1c
	.word @song0ref6
	.byte $48, $49, .lobyte(@env1), .hibyte(@env1), $4a, $2a, $eb, $00, $d1, $49, .lobyte(@env30), .hibyte(@env30), $9c, $17
	.byte $8b, $9c, $18, $89
@song0ref71:
	.byte $48, $49, .lobyte(@env30), .hibyte(@env30), $19, $a7, $00, $8b, $78, $9c, $19, $99, $73, $8d, $19, $89, $7f, $25, $99
	.byte $00, $8b, $74, $25, $8b, $7f, $22, $99, $00, $87, $74, $83, $22, $89, $48, $7f, $20, $99, $00, $87, $74, $83, $20, $8b
	.byte $7f, $1e, $b3, $1d, $b5, $1e, $b3, $48, $20, $b5, $77, $20, $99, $73, $20, $97, $7f, $29, $d1, $28, $8b, $27, $89, $48
	.byte $49, .lobyte(@env30), .hibyte(@env30), $25, $ff, $a3, $73, $9c, $25, $b3, $48, $7f, $49, .lobyte(@env30), .hibyte(@env30)
	.byte $1b, $a7, $00, $8b, $73, $9c, $1b, $8b, $75, $1b, $8b, $73, $1b, $97, $7f, $25, $99, $00, $8b, $74, $25, $8b, $7f, $22
	.byte $99, $00, $8b, $74, $22, $89, $48, $7f, $20, $99, $00, $8b, $74, $20, $8b, $7f, $1e, $b3, $20, $b5, $22, $b3, $48, $1d
	.byte $b5, $75, $1d, $99, $72, $1d, $97, $7f, $20, $b5, $75, $20, $99, $72, $20, $97, $48, $7f, $20, $b5, $1e, $b3, $1d, $b5
	.byte $1e, $b3
	.byte $41, $6a
	.word @song0ref71
	.byte $48, $9a
@song0ref232:
	.byte $31, $b5, $2a, $b3, $2c, $b5, $2a, $b3, $48, $24, $b5, $2a, $b3, $2c, $b5, $2a, $b3, $48, $23, $b5, $2a, $b3, $2c, $b5
	.byte $2f, $b3, $48, $2e, $b5, $2c, $b3, $2a, $b5, $25, $b3, $48
	.byte $41, $20
	.word @song0ref232
	.byte $48
	.byte $41, $20
	.word @song0ref232
	.byte $48, $31, $b1, $7e, $83, $2a, $b3, $7d, $2c, $b1, $7c, $83, $2a, $b3, $48, $7b, $24, $b5, $7a, $2a, $b3, $79, $2c, $b5
	.byte $2a, $81, $78, $b1, $48, $77, $23, $b5, $2a, $81, $76, $b1, $75, $2c, $b5, $74, $2f, $b3, $48, $73, $2e, $b5, $72, $2c
	.byte $b3, $71, $2a, $b5, $70, $25, $b3, $44, $00
@song0ch1:
	.byte $73
@song0ref334:
	.byte $49, .lobyte(@env31), .hibyte(@env31), $b7, $98, $25, $b3, $00, $b5, $31, $b3, $00, $b5, $2c, $eb, $00, $b3, $b7, $2a
	.byte $b3, $00, $b5, $31, $b3, $00, $b5, $25, $eb, $00, $b3, $b7, $25, $b3, $00, $b5, $2a, $b3, $00, $b5, $31, $b3, $00, $b5
	.byte $33, $b3, $00, $b5, $31, $b3, $00, $b5, $2c, $b3, $00, $b5, $2a, $eb, $00, $b3
	.byte $41, $37
	.word @song0ref334
	.byte $7f, $96
@song0ref398:
	.byte $0b, $8b, $00, $8b, $74, $0b
@song0ref404:
	.byte $8b, $00, $8b, $7f, $12, $8b, $00, $8b, $74, $12, $8b, $00, $89, $7f, $14, $8b, $00, $8b, $74, $14, $8b, $00, $8b, $7f
	.byte $12, $8b, $00, $8b, $74, $12, $8b, $00, $89, $7f
	.byte $41, $20
	.word @song0ref398
	.byte $7f, $0a, $8b, $00, $8b, $74, $0a
	.byte $41, $1b
	.word @song0ref404
	.byte $7f, $08, $8b, $00, $8b, $74, $08
	.byte $41, $1b
	.word @song0ref404
	.byte $7f, $08, $8b, $00, $8b, $74, $08
	.byte $41, $1b
	.word @song0ref404
	.byte $7f, $0d, $8b, $00, $8b, $74, $0d
	.byte $41, $1b
	.word @song0ref404
	.byte $7f, $0a, $8b, $00, $8b, $74, $0a
	.byte $41, $1b
	.word @song0ref404
@song0ref491:
	.byte $7f, $0f, $8b, $00, $8b, $74, $0f, $8b, $00, $8b, $7f, $12, $8b, $00, $8b, $74, $12, $8b, $00, $89, $7f, $11, $8b, $00
	.byte $8b, $74, $11, $8b, $00, $8b, $7f, $0d, $8b, $00, $8b, $74, $0d, $8b, $00, $89, $7f
	.byte $41, $20
	.word @song0ref398
	.byte $7f
	.byte $41, $20
	.word @song0ref398
	.byte $7f, $0a, $8b, $00, $8b, $74, $0a
	.byte $41, $1b
	.word @song0ref404
	.byte $7f, $08, $8b, $00, $8b, $74, $08
	.byte $41, $1b
	.word @song0ref404
	.byte $7f, $08, $8b, $00, $8b, $74, $08
	.byte $41, $1b
	.word @song0ref404
	.byte $7f, $0d, $8b, $00, $8b, $74, $0d
	.byte $41, $1b
	.word @song0ref404
	.byte $7f, $0a, $8b, $00, $8b, $74, $0a
	.byte $41, $1b
	.word @song0ref404
	.byte $41, $20
	.word @song0ref491
	.byte $7f, $49, .lobyte(@env30), .hibyte(@env30), $9b, $94
@song0ref598:
	.byte $31, $99, $00, $99, $2a, $97, $00, $99, $2c, $99, $00, $99, $2a, $97, $00, $99, $24, $99, $00, $99, $2a, $97, $00, $99
	.byte $2c, $99, $00, $99, $2a, $97, $00, $99, $23, $99, $00, $99, $2a, $97, $00, $99, $2c, $99, $00, $99, $2f, $97, $00, $99
	.byte $2e, $99, $00, $99, $2c, $97, $00, $99, $2a, $99, $00, $99, $25, $97, $00, $99
	.byte $41, $40
	.word @song0ref598
	.byte $41, $40
	.word @song0ref598
	.byte $31, $99, $00, $99, $7e, $2a, $97, $00, $99, $7d, $2c, $99, $00, $99, $7c, $2a, $97, $00, $99, $7b, $24, $99, $00, $99
	.byte $7a, $2a, $97, $00, $99, $79, $2c, $99, $00, $99, $78, $2a, $97, $00, $99, $77, $23, $99, $00, $99, $76, $2a, $97, $00
	.byte $99, $75, $2c, $99, $00, $99, $74, $2f, $97, $00, $99, $73, $2e, $99, $00, $99, $72, $2c, $97, $00, $99, $71, $2a, $99
	.byte $00, $99, $70, $25, $97, $44, $00
@song0ch2:
	.byte $49, .lobyte(@env29), .hibyte(@env29), $84
@song0ref752:
	.byte $1e, $ff, $d9, $84, $22, $ff, $d9, $21, $ff, $d9, $20, $ff, $d9, $1e, $ff, $d9, $22, $ff, $d9, $21, $ff, $d9, $20, $ff
	.byte $a3, $00, $b3, $49, .lobyte(@env29), .hibyte(@env29)
	.byte $41, $1a
	.word @song0ref752
@song0ref785:
	.byte $17, $ff, $d9, $ff, $db, $16, $ff, $d9, $15, $ff, $d9, $14, $ff, $d9, $19, $ff, $d9, $16, $ff, $d9, $1b, $eb, $19, $eb
	.byte $41, $18
	.word @song0ref785
	.byte $2a, $ff, $d9, $2c, $ff, $d9, $23, $ff, $d9, $2a, $ff, $d9, $2a, $ff, $d9, $2c, $ff, $d9, $23, $ff, $d9, $2a, $ff, $d9
	.byte $00, $ff, $d9, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $44, $00
@song0ch3:
@song0ref856:
	.byte $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db, $ff, $db
	.byte $41, $10
	.word @song0ref856
	.byte $77, $9e
@song0ref877:
	.byte $16, $99, $00, $99, $74, $1f, $99, $00, $97, $7b, $1b, $99, $00, $cf, $77, $16, $99, $00, $99, $74, $1f, $99, $00, $97
	.byte $7b, $1b, $99, $00, $cf, $77
	.byte $41, $18
	.word @song0ref877
	.byte $77
	.byte $41, $18
	.word @song0ref877
	.byte $77
	.byte $41, $18
	.word @song0ref877
	.byte $77
	.byte $41, $18
	.word @song0ref877
	.byte $77
	.byte $41, $18
	.word @song0ref877
	.byte $77
	.byte $41, $18
	.word @song0ref877
	.byte $77
	.byte $41, $18
	.word @song0ref877
@song0ref934:
	.byte $77, $16, $99, $00, $99, $75, $1f, $99, $00, $e7, $73, $81, $17, $99, $77, $16, $99, $00, $99, $75, $1f, $99, $00, $97
	.byte $1b, $99, $00, $cf
	.byte $41, $17
	.word @song0ref934
	.byte $41, $17
	.word @song0ref934
	.byte $41, $17
	.word @song0ref934
	.byte $41, $10
	.word @song0ref856
	.byte $44, $00
@song0ch7:
@song0ch6:
@song0ch5:
@song0ch4:
	.byte $41, $10
	.word @song0ref856
	.byte $41, $10
	.word @song0ref856
	.byte $41, $10
	.word @song0ref856
	.byte $41, $10
	.word @song0ref856
	.byte $41, $10
	.word @song0ref856
	.byte $41, $10
	.word @song0ref856
	.byte $44, $00
@song1ch0:
@song1ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $f7, $48, $ff, $f7, $48, $8a, $27, $81, $28, $83, $29
	.byte $8b, $00, $85, $28, $8d, $27, $83, $00, $85, $28, $8d, $00, $8d, $26, $87, $00, $83, $24, $83, $00, $85, $23, $87, $00
	.byte $93, $21, $87, $00, $83, $20, $83, $00, $85, $21, $87, $00, $93, $1c, $87, $00, $83, $1d, $83, $00, $85, $48, $1c, $87
	.byte $00, $83, $1d, $85, $00, $85, $1c, $87, $00, $83, $1b, $83, $00, $85, $1c, $87, $00, $83, $20, $85, $00, $85, $24, $87
	.byte $00, $83, $23, $83, $00, $85, $21, $8d, $00, $8d, $21, $87, $00, $83, $23, $83, $00, $85, $24, $8d, $00, $8d, $23, $87
	.byte $00, $83, $24, $83, $00, $85, $48, $26, $8d, $00, $8d, $24, $87, $00, $83, $23, $83, $00, $85, $20, $8d, $00, $8d, $20
	.byte $87, $00, $83, $23, $83, $00, $85, $24, $8d, $00, $e9, $48, $ff, $f7, $48, $ff, $f7, $48, $ff, $f7, $48, $ff, $f7, $48
	.byte $ff, $f7, $48, $ff, $f7, $48, $ff, $f7, $48, $ff, $f7, $48, $ff, $f7, $48, $ff, $f7, $48, $ff, $f7, $42
	.word @song1ch0loop
@song1ch7:
@song1ch6:
@song1ch2:
@song1ch1:
@song1ch1loop:
@song1ref188:
	.byte $ff, $f7, $ff, $f7, $ff, $f7, $ff, $f7, $ff, $f7, $ff, $f7, $ff, $f7, $ff, $f7, $ff, $f7, $ff, $f7, $ff, $f7, $ff, $f7
	.byte $ff, $f7, $ff, $f7, $ff, $f7, $ff, $f7, $42
	.word @song1ch1loop
@song1ch3:
@song1ch3loop:
	.byte $7b, $4f, $01, $92, $3f, $a7, $00, $83, $3f, $83, $00, $85, $3d, $87, $00, $93, $3d, $87, $00, $91, $3c, $9d, $00, $8d
	.byte $3c, $83, $00, $85, $3a, $a7, $00, $91, $38, $95, $00, $95, $38, $83, $00, $85, $38, $87, $00, $93, $38, $87, $00, $91
	.byte $39, $bb, $00, $bb
@song1ref276:
	.byte $38, $87, $00, $83, $38, $85, $00, $85, $38, $87, $00, $83, $38, $83, $00, $85, $3d, $87, $00, $83, $38, $85, $00, $85
	.byte $38, $87, $00, $83, $38, $83, $00, $85, $39, $87, $00, $83, $39, $85, $00, $85, $39, $87, $00, $83, $39, $83, $00, $85
	.byte $3e, $87, $00, $83, $39, $85, $00, $85, $39, $87, $00, $83, $39, $83, $00, $85
	.byte $41, $40
	.word @song1ref276
	.byte $41, $40
	.word @song1ref276
	.byte $ff, $f7
	.byte $41, $40
	.word @song1ref276
	.byte $41, $40
	.word @song1ref276
	.byte $41, $40
	.word @song1ref276
	.byte $ff, $f7
	.byte $41, $40
	.word @song1ref276
	.byte $41, $40
	.word @song1ref276
	.byte $41, $40
	.word @song1ref276
	.byte $ff, $f7, $ff, $f7, $ff, $f7, $42
	.word @song1ch3loop
@song1ch4:
@song1ch4loop:
	.byte $ff, $f7, $ff, $f7
@song1ref382:
	.byte $09, $9d, $0b, $9b, $0a, $9d, $0b, $9b, $09, $9d, $0b, $9b, $0a, $9d, $0b, $9b, $09, $9d, $0b, $9b, $0a, $9d, $0b, $9b
	.byte $41, $18
	.word @song1ref382
	.byte $41, $18
	.word @song1ref382
	.byte $41, $18
	.word @song1ref382
	.byte $41, $18
	.word @song1ref382
	.byte $41, $18
	.word @song1ref382
	.byte $41, $18
	.word @song1ref382
	.byte $41, $18
	.word @song1ref382
	.byte $00, $ff, $f5, $ff, $f7, $42
	.word @song1ch4loop
@song1ch5:
@song1ch5loop:
	.byte $ff, $f7, $ff, $f7, $9f, $76, $90, $27, $81, $28, $83, $29, $89, $00, $85, $28, $8d, $27, $85, $00, $85, $28, $8d, $00
	.byte $8b, $26, $87, $00, $83, $24, $85, $00, $85, $23, $87, $00, $91, $21, $87, $00, $83, $20, $85, $00, $85, $21, $87, $00
	.byte $91, $1c, $87, $00, $83, $1d, $85, $00, $85, $1c, $87, $00, $83, $1d, $83, $00, $85, $1c, $87, $00, $83, $1b, $85, $00
	.byte $85, $1c, $87, $00, $83, $20, $83, $00, $85, $24, $87, $00, $83, $23, $85, $00, $85, $21, $8d, $00, $8b, $21, $87, $00
	.byte $83, $23, $85, $00, $85, $24, $8d, $00, $8b, $23, $87, $00, $83, $24, $85, $00, $85, $26, $8d, $00, $8b, $24, $87, $00
	.byte $83, $23, $85, $00, $85, $20, $8d, $00, $8b, $20, $87, $00, $83, $23, $85, $00, $85, $24, $8d, $00, $c9
	.byte $41, $16
	.word @song1ref188
	.byte $42
	.word @song1ch5loop
@song2ch0:
@song2ch0loop:
	.byte $4c, $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $4e, $04
@song2ref8:
	.byte $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48
	.byte $41, $10
	.word @song2ref8
	.byte $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $b3, $88, $50, $fc, $3d, $42, $9b, $36, $9b
@song2ref55:
	.byte $48, $2e, $87, $00, $91, $2e, $87, $00, $83, $2e, $8b, $00, $8d, $2e, $8b, $00, $8d, $2e, $9b, $2c, $8b, $00, $8d, $2c
	.byte $bf, $00, $85
	.byte $41, $10
	.word @song2ref55
	.byte $2c, $8b, $00, $8d, $2e, $8b, $00, $8d, $33, $8b, $00, $8d, $2e, $8b, $2c, $9b, $48, $33, $8d, $00, $8b, $2e, $8d, $00
	.byte $8b, $2c, $8d, $00, $8b, $2a, $8d, $00, $8b, $31, $8d, $00, $8b, $2e, $8d, $00, $8b, $2c, $8d, $00, $8b, $2a, $8d, $00
	.byte $8b, $48, $27, $8d, $00, $8b, $29, $8d, $2a, $8b, $00, $8d, $2e, $8b, $00, $8d, $31, $f5, $00, $8b, $48, $f7, $86
@song2ref156:
	.byte $2a, $8d, $27, $8b, $2a, $8d, $2c, $8b, $2d, $8d, $2c, $8b, $2a, $8d, $27, $8b, $48, $2d, $87, $43, $2c, $83, $43, $2a
	.byte $83, $43, $27, $85, $2a, $9b, $2c, $f5, $00, $8d, $2d, $8b, $00, $8d, $2e, $8b, $48, $31, $9b, $2e, $8d, $2d, $8b, $2c
	.byte $8d, $2a, $8b, $27, $8d, $29, $8b, $2a, $9b, $2c, $9b, $2e, $9b, $31, $9b, $48, $32, $9b, $2d, $9b, $2d, $8d, $2c, $8b
	.byte $2a, $8d, $2c, $e5, $00, $9b, $48, $1e, $9b, $20, $9b, $22, $9b, $2a, $9b, $29, $b9, $27, $b9, $48, $29, $b9, $2a, $b9
	.byte $2c, $b9, $29, $b9, $48, $2e, $e7, $00, $8b, $2e, $8d, $2d, $8b, $2c, $8d, $2b, $8b, $2a, $8d, $29, $8b, $28, $8d, $27
	.byte $8b, $48, $26, $f5, $28, $e7, $00, $8b, $48, $f7
	.byte $41, $70
	.word @song2ref156
	.byte $48, $21, $f5, $23, $f5, $48, $7c, $4b, .lobyte(@env6), .hibyte(@env6)
@song2ref299:
	.byte $17, $ff, $b1, $4d, $1e, $b9, $48, $4d, $1d, $f5, $4d, $1b, $f5, $48, $4d, $1e, $ff, $ed, $48, $00, $ff, $ed, $48, $4d
	.byte $17, $ff, $b1, $4d, $1e, $b9, $48, $4d, $1d, $f5, $4d, $1b, $f5, $48, $4d, $1b, $ff, $ed, $48, $00, $ff, $ed, $48, $4d
	.byte $41, $18
	.word @song2ref299
	.byte $48, $00, $9b, $4b, .lobyte(@env13), .hibyte(@env13), $8a
@song2ref357:
	.byte $2a, $9b, $4d, $29, $9b, $00, $8d, $4d, $25, $8b, $00, $8d, $4d, $29, $8b, $00, $8d, $4d, $27, $9b, $4d, $22, $8b, $4d
	.byte $25, $8d, $4d, $27, $8b, $48, $00, $9b, $4d
	.byte $41, $17
	.word @song2ref357
	.byte $ff, $ed, $48
	.byte $41, $10
	.word @song2ref8
	.byte $48
	.byte $41, $10
	.word @song2ref8
	.byte $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $48, $ff, $ef, $42
	.word @song2ch0loop
@song2ch1:
@song2ch1loop:
@song2ref428:
	.byte $4e, $04
@song2ref430:
	.byte $ff
@song2ref431:
	.byte $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff
	.byte $ef, $ff, $ef, $ff, $ef, $ff, $b3, $88, $25, $9b, $43, $50, $f8, $31, $36, $9b
@song2ref471:
	.byte $2a, $87, $00, $91, $2a, $87, $00, $83, $2a, $8b, $00, $8d, $2a, $8b, $00, $8d, $2a, $9b, $27, $8b, $00, $8d, $27, $bf
	.byte $00, $85
@song2ref497:
	.byte $2a, $87, $00, $91, $2a, $87, $00, $83, $2a, $8b, $00, $8d, $2c, $8b, $00, $8d, $2d, $9b, $2c, $8b, $2a, $8d, $27, $83
	.byte $00, $85, $2a, $8d, $2c, $8b, $00, $9b
	.byte $41, $12
	.word @song2ref497
	.byte $2e, $8b, $00, $8d, $31, $9b, $2e, $8b, $00, $9b, $33, $87, $00, $91, $33, $8d, $00, $8b, $33, $87, $00, $83, $2e, $8b
	.byte $33, $87, $00, $83, $31, $ff, $83
	.byte $41, $26
	.word @song2ref471
	.byte $2a, $8b, $00, $8d, $27, $8b, $00, $8d, $2a, $8b, $00, $8d, $2e, $8b, $00, $8d, $2a, $8b, $27, $9b, $2e, $8d, $00, $8b
	.byte $2a, $8d, $00, $8b, $29, $8d, $00, $8b, $27, $8d, $00, $8b, $2a, $8d, $00, $8b, $27, $8d, $00, $8b, $25, $8d, $00, $8b
	.byte $22, $8d, $00, $8b, $23, $8d, $00, $8b, $25, $8d, $27, $8b, $00, $8d, $29, $8b, $00, $8d, $2a, $f5, $00, $8b, $f7, $86
@song2ref638:
	.byte $27, $8d, $23, $8b, $27, $8d, $29, $8b, $2a, $8d, $29, $8b, $27, $8d, $23, $8b, $2a, $87, $43, $29, $83, $43, $27, $83
	.byte $43, $23, $85, $27, $9b, $29, $f5, $00, $8d, $29, $8b, $00, $8d, $2a, $8b, $2c, $9b, $29, $8d, $28, $8b, $27, $8d, $25
	.byte $8b, $22, $8d, $24, $8b, $25, $9b, $27, $9b, $29, $9b, $2c, $9b, $2d, $9b, $28, $9b, $28, $8d, $27, $8b, $25, $8d, $27
	.byte $e5, $00, $9b, $1b, $9b, $1d, $9b, $1e, $9b, $27, $9b, $25, $b9, $23, $b9, $25, $b9, $27, $b9, $29, $b9, $25, $b9, $27
	.byte $e7, $00, $8b, $27, $8d, $26, $8b, $25, $8d, $24, $8b, $23, $8d, $22, $8b, $21, $8d, $20, $8b, $1f, $f5, $21, $e7, $00
	.byte $8b, $f7
	.byte $41, $70
	.word @song2ref638
	.byte $26, $f5, $28, $f5, $7d
@song2ref768:
	.byte $0b, $ff, $ed, $0d, $ff, $ed, $0c, $ff, $ed, $0c, $ff, $ed, $0b, $ff, $ed, $0d, $ff, $ed, $00, $ff, $ed, $ff, $ef
	.byte $41, $17
	.word @song2ref768
	.byte $41, $1f
	.word @song2ref430
	.byte $41, $11
	.word @song2ref431
	.byte $42
	.word @song2ch1loop
@song2ch2:
@song2ch2loop:
	.byte $4c, $4e, $04, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $8e, $1b, $ff, $ed, $19, $ff, $ed, $18, $ff, $ed, $17, $f5, $19
	.byte $f5
@song2ref829:
	.byte $1b, $ff, $cf, $27, $9b, $19, $ff, $cf, $25, $9b, $18, $ff, $cf, $24, $9b, $17, $e7, $19, $e5, $25, $9b
	.byte $41, $15
	.word @song2ref829
@song2ref853:
	.byte $00, $ff, $ed, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef
@song2ref870:
	.byte $17, $ff, $cf, $23, $9b, $19, $ff, $cf, $25, $9b, $1b, $ff, $cf, $27, $9b, $1a, $f5, $1c, $d7, $28, $9b
	.byte $41, $15
	.word @song2ref870
	.byte $41, $15
	.word @song2ref870
	.byte $41, $15
	.word @song2ref870
@song2ref900:
	.byte $17, $ff, $cf, $23, $9b, $19, $ff, $cf, $25, $9b, $18, $ff, $cf, $24, $9b, $18, $ff, $cf
@song2ref918:
	.byte $24, $9b, $17, $ff, $cf, $23, $9b, $19, $ff, $cf, $25, $9b, $1b, $ff, $cf, $27, $9b, $1b, $ff, $cf, $27, $9b
	.byte $41, $1e
	.word @song2ref900
	.byte $00, $9b, $4b, .lobyte(@env13), .hibyte(@env13)
	.byte $41, $16
	.word @song2ref357
	.byte $00, $9b, $4d
	.byte $41, $16
	.word @song2ref357
	.byte $4b, .lobyte(@env19), .hibyte(@env19), $4c
@song2ref961:
	.byte $17, $ff, $cf, $23, $9b, $19, $ff, $cf, $25, $9b, $1b, $d7, $27, $9b, $1a, $d7, $26, $9b, $19, $d7, $25, $9b, $18, $d7
	.byte $41, $16
	.word @song2ref918
	.byte $41, $18
	.word @song2ref961
	.byte $41, $16
	.word @song2ref918
	.byte $41, $11
	.word @song2ref853
	.byte $42
	.word @song2ch2loop
@song2ch3:
@song2ch3loop:
	.byte $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef
@song2ref1015:
	.byte $ff, $87, $77, $51, $01, $a0, $82, $1e, $9b, $80, $1e, $9b, $1e, $8b
@song2ref1029:
	.byte $1e, $9b, $1e, $9b, $1e, $9b, $1e, $9b, $1e, $9b, $1e, $9b, $1e, $9b, $1e, $9b
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $1e, $9b
@song2ref1053:
	.byte $1e, $9b, $1e, $9b, $1e, $9b, $1e, $9b, $1e, $8d, $7c, $51, $01, $f0, $82, $1c, $9b, $80, $1e, $9b, $1e, $8b, $1e, $9b
	.byte $7a
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $12
	.word @song2ref1053
	.byte $7a
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $12
	.word @song2ref1053
	.byte $7a
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $12
	.word @song2ref1053
	.byte $7a
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $12
	.word @song2ref1053
	.byte $7a
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $12
	.word @song2ref1053
	.byte $7a
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $12
	.word @song2ref1053
	.byte $7a
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $12
	.word @song2ref1053
	.byte $7a
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $12
	.word @song2ref1053
	.byte $7a
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $12
	.word @song2ref1053
	.byte $7a
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $12
	.word @song2ref1053
	.byte $7a
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $00, $ff, $ed
	.byte $41, $18
	.word @song2ref1015
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $41, $10
	.word @song2ref1029
	.byte $1e, $9b
	.byte $41, $11
	.word @song2ref853
	.byte $42
	.word @song2ch3loop
@song2ch4:
@song2ch4loop:
	.byte $41, $10
	.word @song2ref430
@song2ref1277:
	.byte $06, $8d, $06, $8b, $07, $9b, $06, $8d, $06, $8b, $07, $9b, $06, $8d, $06, $8b, $07, $8d, $06, $9b, $06, $8b, $07, $9b
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $00, $9b, $05, $9b, $03, $9b, $00, $8d, $04, $8b, $00, $8d, $03, $8b, $00, $8d, $02, $9b, $01, $8b, $04, $8d, $02, $8b
	.byte $00, $9b, $05, $9b, $03, $9b, $00, $8d, $07, $8b, $06, $9b, $07, $8d, $06, $9b, $07, $8b, $06, $9b
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $18
	.word @song2ref1277
	.byte $41, $11
	.word @song2ref853
	.byte $42
	.word @song2ch4loop
@song2ch5:
@song2ch5loop:
	.byte $4c, $4e, $04, $8c
@song2ref1539:
	.byte $1b, $8d, $1b
@song2ref1542:
	.byte $8b, $27, $8d, $00, $8b, $22, $8d, $00, $9b, $21, $8b, $00, $8d, $20, $8b, $00, $8d, $1e, $9b, $1b, $8b, $1e, $8d, $20
	.byte $8b, $19, $8d, $19
	.byte $41, $19
	.word @song2ref1542
	.byte $18, $8d, $18
	.byte $41, $19
	.word @song2ref1542
	.byte $17, $8d, $17
	.byte $41, $19
	.word @song2ref1542
	.byte $4e, $04
	.byte $41, $1f
	.word @song2ref1539
	.byte $41, $19
	.word @song2ref1542
	.byte $18, $8d, $18
	.byte $41, $19
	.word @song2ref1542
	.byte $17, $8d, $17
	.byte $41, $19
	.word @song2ref1542
	.byte $4b, .lobyte(@env13), .hibyte(@env13)
@song2ref1608:
	.byte $1b, $8d, $4d, $1b
@song2ref1612:
	.byte $8b, $4d, $27, $8d, $00, $8b, $4d, $22, $8d, $00, $9b, $4d, $21, $8b, $00, $8d, $4d, $20, $8b, $00, $8d, $4d, $1e, $9b
	.byte $4d, $1b, $8b, $4d, $1e, $8d, $4d, $20, $8b, $4d, $19, $8d, $4d, $19
	.byte $41, $19
	.word @song2ref1612
	.byte $4d, $18, $8d, $4d, $18
	.byte $41, $19
	.word @song2ref1612
	.byte $4d, $17, $8d, $4d, $17
	.byte $41, $19
	.word @song2ref1612
	.byte $4d
	.byte $41, $1f
	.word @song2ref1608
	.byte $41, $19
	.word @song2ref1612
	.byte $4d, $18, $8d, $4d, $18
	.byte $41, $19
	.word @song2ref1612
	.byte $4d, $17, $8d, $4d, $17
	.byte $41, $19
	.word @song2ref1612
	.byte $00, $ff, $ed, $ff, $ef, $ff, $ef, $ff, $e1, $77, $8d, $4e, $04, $4b, .lobyte(@env19), .hibyte(@env19), $4c
	.byte $41, $1f
	.word @song2ref1539
	.byte $41, $19
	.word @song2ref1542
	.byte $18, $8d, $18
	.byte $41, $19
	.word @song2ref1542
	.byte $17, $8d, $17
	.byte $41, $19
	.word @song2ref1542
	.byte $41, $11
	.word @song2ref853
	.byte $41, $10
	.word @song2ref430
	.byte $4e, $04
	.byte $41, $1f
	.word @song2ref1539
	.byte $41, $19
	.word @song2ref1542
	.byte $18, $8d, $18
	.byte $41, $19
	.word @song2ref1542
	.byte $78
@song2ref1748:
	.byte $00, $8d, $27, $8b, $2a, $8d, $27, $8b, $2c, $8d, $00, $8b, $2a, $8d, $00, $8b, $27, $8d, $25, $8b, $00, $8d, $22, $8b
	.byte $00, $8d, $20, $8b, $22, $8d, $25, $8b, $00, $ff, $ed, $ff, $ef, $ff, $ef, $ff, $ef, $4e, $04
	.byte $41, $1f
	.word @song2ref1539
	.byte $41, $19
	.word @song2ref1542
	.byte $18, $8d, $18
	.byte $41, $19
	.word @song2ref1542
	.byte $41, $20
	.word @song2ref1748
	.byte $7c, $23, $ff, $b1, $2a, $b9, $29, $f5, $27, $f5
	.byte $41, $11
	.word @song2ref853
	.byte $41, $10
	.word @song2ref430
	.byte $4e, $04
	.byte $41, $1c
	.word @song2ref1539
	.byte $4e, $04
	.byte $41, $1c
	.word @song2ref1539
	.byte $4e, $04, $17, $8d, $17
	.byte $41, $19
	.word @song2ref1542
	.byte $4e, $04, $19, $8d, $19
	.byte $41, $19
	.word @song2ref1542
	.byte $4e, $04
	.byte $41, $1c
	.word @song2ref1539
	.byte $4e, $04
	.byte $41, $1c
	.word @song2ref1539
	.byte $4e, $04, $17, $8d, $17
	.byte $41, $19
	.word @song2ref1542
	.byte $4e, $04, $19, $8d, $19
	.byte $41, $19
	.word @song2ref1542
	.byte $4e, $04
	.byte $41, $1c
	.word @song2ref1539
	.byte $4e, $04
	.byte $41, $1c
	.word @song2ref1539
	.byte $42
	.word @song2ch5loop
@song2ch6:
@song2ch6loop:
	.byte $41, $1f
	.word @song2ref428
	.byte $41, $1e
	.word @song2ref431
	.byte $41, $1e
	.word @song2ref431
	.byte $ef, $ff, $ef, $ff, $ef, $7c, $8c, $17, $ff, $b1, $1e, $b9, $1d, $f5, $1b, $f5, $1e, $ff, $ed, $78, $00, $8d, $1b, $8b
	.byte $1e, $8d, $1b, $8b, $20, $8d, $00, $8b, $1e, $8d, $00, $8b, $1b, $8d, $19, $8b, $00, $8d, $16, $8b, $00, $8d, $14, $8b
	.byte $16, $8d, $19, $8b, $7c, $17, $ff, $b1, $1e, $b9, $1d, $f5, $1b, $f5
	.byte $41, $11
	.word @song2ref853
	.byte $41, $1f
	.word @song2ref430
	.byte $ef, $ff, $ef, $ff, $ef, $42
	.word @song2ch6loop
@song2ch7:
@song2ch7loop:
	.byte $4c, $4e, $04, $ff, $ef, $ff, $ef, $ff, $ef, $ff, $ef, $a0
@song2ref1986:
	.byte $03, $8d, $00, $8b, $03, $8d, $00, $8b, $03, $8d, $03, $8b, $00, $8d, $03, $8b, $00, $8d, $03, $8b, $00, $8d, $03, $8b
	.byte $03, $8d, $03, $8b, $03
@song2ref2015:
	.byte $8d, $00, $8b, $01, $8d, $00, $8b, $01, $8d, $00, $8b, $01, $8d, $01, $8b, $00, $8d, $01
@song2ref2033:
	.byte $8b, $00, $8d, $01, $8b, $00, $8d, $01, $8b, $01, $8d, $01, $8b, $01, $8d, $00, $8b
@song2ref2050:
	.byte $40, $0c, $8d, $00, $8b, $40, $0c, $8d, $00, $8b, $40, $0c, $8d, $40, $0c, $8b, $00, $8d, $40, $0c, $8b, $00, $8d
@song2ref2073:
	.byte $40, $0c, $8b, $00, $8d, $40, $0c, $8b, $40, $0c, $8d, $40, $0c, $8b, $40, $0c
@song2ref2089:
	.byte $8d, $00, $8b, $40, $0b, $8d, $00, $8b, $40, $0b, $8d, $00, $8b, $40, $0b, $8d, $40, $0b, $8b, $00, $8d, $40, $0b
	.byte $41, $11
	.word @song2ref2033
	.byte $41, $6f
	.word @song2ref1986
	.byte $41, $11
	.word @song2ref2033
	.byte $41, $6f
	.word @song2ref1986
	.byte $41, $11
	.word @song2ref2033
	.byte $41, $6f
	.word @song2ref1986
	.byte $41, $11
	.word @song2ref2033
	.byte $41, $6f
	.word @song2ref1986
	.byte $41, $11
	.word @song2ref2033
@song2ref2139:
	.byte $40, $0b, $8d, $00, $8b, $40, $0b, $8d, $00, $8b, $40, $0b, $8d, $40, $0b, $8b, $00, $8d, $40, $0b, $8b, $00, $8d, $40
	.byte $0b, $8b, $00, $8d, $40, $0b, $8b, $40, $0b, $8d, $40, $0b, $8b, $40, $0b
	.byte $41, $23
	.word @song2ref2015
	.byte $41, $20
	.word @song2ref1986
@song2ref2184:
	.byte $02, $8d, $00, $8b, $02, $8d, $00, $8b, $02, $8d, $02, $8b, $00, $8d, $02, $8b, $00, $8d, $04, $8b, $00, $8d, $04, $8b
	.byte $04, $8d, $04, $8b, $04
	.byte $41, $12
	.word @song2ref2089
	.byte $8b, $00, $8d, $40, $0b, $8b, $00, $8d, $40, $0b, $8b, $40, $0b, $8d, $40, $0b, $8b, $40, $0b
	.byte $41, $23
	.word @song2ref2015
	.byte $41, $20
	.word @song2ref1986
	.byte $41, $1d
	.word @song2ref2184
	.byte $41, $12
	.word @song2ref2089
	.byte $8b, $00, $8d, $40, $0b, $8b, $00, $8d, $40, $0b, $8b, $40, $0b, $8d, $40, $0b, $8b, $40, $0b
	.byte $41, $23
	.word @song2ref2015
	.byte $41, $20
	.word @song2ref1986
	.byte $41, $1d
	.word @song2ref2184
	.byte $41, $12
	.word @song2ref2089
	.byte $8b, $00, $8d, $40, $0b, $8b, $00, $8d, $40, $0b, $8b, $40, $0b, $8d, $40, $0b, $8b, $40, $0b
	.byte $41, $23
	.word @song2ref2015
	.byte $41, $20
	.word @song2ref1986
	.byte $41, $1d
	.word @song2ref2184
	.byte $41, $12
	.word @song2ref2089
	.byte $8b, $00, $8d, $40, $0b, $8b, $00, $8d, $40, $0b, $8b, $40, $0b, $8d, $40, $0b, $8b, $40, $0b
	.byte $41, $43
	.word @song2ref2015
	.byte $41, $2f
	.word @song2ref2050
	.byte $8b, $00, $8d, $40, $0b, $8b, $00, $8d, $40, $0b, $8b, $40, $0b, $8d, $40, $0b, $8b, $40, $0b
	.byte $41, $23
	.word @song2ref2015
	.byte $41, $20
	.word @song2ref1986
	.byte $41, $20
	.word @song2ref1986
	.byte $41, $1d
	.word @song2ref2139
	.byte $41, $43
	.word @song2ref2015
	.byte $41, $2f
	.word @song2ref2050
	.byte $8b, $00, $8d, $40, $0b, $8b, $00, $8d, $40, $0b, $8b, $40, $0b, $8d, $40, $0b, $8b, $40, $0b
	.byte $41, $23
	.word @song2ref2015
	.byte $00, $9b, $4b, .lobyte(@env6), .hibyte(@env6)
@song2ref2398:
	.byte $06, $9b, $4d, $05, $9b, $00, $8d, $4d, $01, $8b, $00, $8d, $4d, $05, $8b, $00, $8d, $4d, $03, $9b, $4d, $40, $0a, $8b
	.byte $4d, $01, $8d, $4d, $03, $8b, $00, $9b, $4d
	.byte $41, $16
	.word @song2ref2398
	.byte $4b, .lobyte(@env19), .hibyte(@env19), $4c
	.byte $41, $1d
	.word @song2ref2139
	.byte $41, $23
	.word @song2ref2015
	.byte $41, $12
	.word @song2ref1986
	.byte $02, $8b, $00, $8d, $02, $8b, $02, $8d, $02, $8b, $02
	.byte $41, $15
	.word @song2ref2015
	.byte $41, $1d
	.word @song2ref2073
	.byte $8b, $00, $8d, $40, $0b, $8b, $00, $8d, $40, $0b, $8b, $40, $0b, $8d, $40, $0b, $8b, $40, $0b
	.byte $41, $23
	.word @song2ref2015
	.byte $41, $20
	.word @song2ref1986
	.byte $41, $20
	.word @song2ref1986
	.byte $41, $1d
	.word @song2ref2139
	.byte $41, $23
	.word @song2ref2015
	.byte $41, $12
	.word @song2ref1986
	.byte $02, $8b, $00, $8d, $02, $8b, $02, $8d, $02, $8b, $02
	.byte $41, $15
	.word @song2ref2015
	.byte $41, $1d
	.word @song2ref2073
	.byte $8b, $00, $8d, $40, $0b, $8b, $00, $8d, $40, $0b, $8b, $40, $0b, $8d, $40, $0b, $8b, $40, $0b
	.byte $41, $23
	.word @song2ref2015
	.byte $41, $20
	.word @song2ref1986
	.byte $41, $20
	.word @song2ref1986
	.byte $41, $10
	.word @song2ref430
	.byte $42
	.word @song2ch7loop
@song3ch0:
@song3ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $ff, $ff, $bf, $42
	.word @song3ch0loop
@song3ch7:
@song3ch6:
@song3ch5:
@song3ch3:
@song3ch2:
@song3ch1:
@song3ch1loop:
	.byte $ff, $ff, $bf, $42
	.word @song3ch1loop
@song3ch4:
@song3ch4loop:
	.byte $0c, $91, $08, $91, $00, $ff, $ff, $95, $42
	.word @song3ch4loop
