; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.export _sounds=sounds

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_snd_txt1
	.word @sfx_ntsc_snd_txt2
	.word @sfx_ntsc_snd_heartbreak1

@sfx_ntsc_snd_txt1:
	.byte $89,$f0,$00
@sfx_ntsc_snd_txt2:
	.byte $8a,$04,$89,$37,$01,$89,$34,$01,$89,$31,$01,$00
@sfx_ntsc_snd_heartbreak1:
	.byte $8a,$82,$89,$3f,$01,$8a,$83,$01,$8a,$85,$01,$8a,$86,$01,$8a,$88
	.byte $01,$8a,$89,$01,$8a,$8b,$01,$8a,$8c,$01,$8a,$8e,$01,$8a,$8f,$00

.export sounds
